import type { NextPage } from 'next';
import Head from 'next/head';

const FourOhFour: NextPage = () => {
  return (
    <div className="flex items-center justify-center h-screen">
      <Head>
        <title>404 - Page not found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <h1 className="p-4 text-4xl font-bold text-center lg:text-7xl">
        404 page not found ⛔
      </h1>
    </div>
  );
};

export default FourOhFour;
