import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div className="flex items-center justify-center h-screen">
      <Head>
        <title>Site under construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <h1 className="p-4 text-4xl font-bold text-center text-white lg:text-7xl">
        Site under construction 🚧
      </h1>
      <div className="absolute -top-64 -left-28">
        <Image
          src="/assets/icons/icon.svg"
          alt="analytics icon"
          height={660}
          width={660}
        />
      </div>
    </div>
  );
};

export default Home;
