import type { NextPage } from 'next';
import Head from 'next/head';
import LandingHero from '@module/LandingHero/LandingHero';
import HomeContent from '@module/HomeContent/HomeContent';
import PricingHero from '@module/PricingHero/PricingHero';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Analytics - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <LandingHero />
      <HomeContent />
      <PricingHero />
    </>
  );
};

export default Home;
