import type { NextPage } from 'next';
import Head from 'next/head';
import LandingHero from '@module/LandingHero/LandingHero';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Analytics - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <LandingHero />
      <div className="h-screen">
        <h1 className="p-4 text-4xl font-bold text-center text-white lg:text-7xl">
          Site under construction 🚧
        </h1>
      </div>
    </>
  );
};

export default Home;
